src/imscam/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from imscam import views
from imscam.drivers.ptz import ptzview
#import ptz_control
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    #url(r'^getconfig$', views.getconfig, name='getconfig'),
    #url(r'^autodetect$', views.autodetect, name='autodetect'),
    url(r'^preview$', views.get_preview_img, name='preview'),
    url(r'^sse_preview$', views.SsePreviewEvents.as_view(), name='sse_preview'),
    url(r'^start_preview$', views.start_preview, name='start_preview'),
    url(r'^stop_preview$', views.stop_preview, name='stop_preview'),
    #url(r'^group/new$', views.new_group, name='new_group'),
    #url(r'^group/save$', views.save_group, name='save_group'),
    #url(r'^group/locations/$', views.ajax_load_locations, name='load_locations'),

    url(r'^ptz_moveleft$', ptzview.ptz_moveleft, name='ptz_moveleft'),
    url(r'^ptz_moveright$', ptzview.ptz_moveright, name='ptz_moveright'),
    url(r'^ptz_moveup$', ptzview.ptz_moveup, name='ptz_moveup'),
    url(r'^ptz_movedown$', ptzview.ptz_movedown, name='ptz_movedown'),
    url(r'^ptz_movecenter$', ptzview.ptz_movecenter, name='ptz_movecenter'),
    url(r'^ptz_moveto$', ptzview.ptz_moveto, name='ptz_moveto'),
    url(r'^ptz_getposition$', ptzview.ptz_getposition, name='ptz_getposition'),
    
    
    #url(r'^snapshot/$', views.snapshot, name='snapshot'),
    
    url(r'^groups/$', views.groups, name='groups'), ###
    url(r'^groups/new/$', views.group_edit, name='group_new'),
    url(r'^groups/(?P<group_id>\d+)/edit/$', views.group_edit, name='group_edit'),
    url(r'^groups/(?P<group_id>\d+)/delete/$', views.group_delete, name='group_delete'),
    
    url(r'^groups/(?P<group_id>\d+)/locations/$', views.locations, name='locations'), ###
    url(r'^groups/(?P<group_id>\d+)/locations/new/$', views.location_edit, name='location_new'),
    url(r'^groups/(?P<group_id>\d+)/locations/(?P<location_id>\d+)/edit/$', views.location_edit, name='location_edit'),
    #url(r'^groups/(?P<group_id>\d+)/locations/load$', views.locations_load, name='locations_load'),
    
    url(r'^locations/update_pan_tilt/$', views.location_update_pan_tilt, name='location_update_pan_tilt'),
    url(r'^groups/locations/(?P<location_id>\d+)/delete/$', views.location_delete, name='location_delete'),
    
    #url(r'^location/$', views.location, name='location'),
    url(r'^copypreview/$', views.copy_preview, name='copypreview'),
    url(r'^groups/(?P<group_id>\d+)/locations/tmp_location_delete/$', views.tmp_location_delete, name='tmp_location_delete'),
    
    url(r'^play_pause/$', views.play_pause, name='play_pause'),
    
    url(r'^browse/$', views.browse_images, name='browse'),
    url(r'^browse/get_files/(?P<location_id>\d+)/$', views.get_files, name='get_files'),
    url(r'^browse/get_files/(?P<location_id>\d+)/(?P<page>\d+)/$', views.get_files, name='get_files_pagination'),
    url(r'^browse/get_latest_locationimage/(?P<locationimage_id>\d+)/$', views.get_latest_locationimage, name='get_latest_locationimage'),
    
    #url(r'^detail/$', views.ajax_get_location_details, name='detail'),
    
    url(r'^settings/$', views.cam_settings, name='cam_settings'),
    
    url(r'^settings/set_config$', views.set_config, name='set_config'),
    
    
    url(r'^help/$', TemplateView.as_view(template_name='imscam/help/about.html'), name='help'),
    url(r'^help/$', TemplateView.as_view(template_name='imscam/help/about.html'), name='help_about'),
    url(r'^help/create_group/$', TemplateView.as_view(template_name='imscam/help/create_group.html'), name='help_create_group'),
    url(r'^help/edit_group/$', TemplateView.as_view(template_name='imscam/help/edit_group.html'), name='help_edit_group'),
    url(r'^help/create_location/$', TemplateView.as_view(template_name='imscam/help/create_location.html'), name='help_create_location'),
    url(r'^help/edit_location/$', TemplateView.as_view(template_name='imscam/help/edit_location.html'), name='help_edit_location'),
    url(r'^help/live_preview/$', TemplateView.as_view(template_name='imscam/help/live_preview.html'), name='help_live_preview'),
    url(r'^help/live_preview_location/$', TemplateView.as_view(template_name='imscam/help/live_preview_location.html'), name='help_live_preview_location'),
    url(r'^help/move_pan_tilt/$', TemplateView.as_view(template_name='imscam/help/move_pan_tilt.html'), name='help_move_pan_tilt'),
    url(r'^help/update_pan_tilt/$', TemplateView.as_view(template_name='imscam/help/update_pan_tilt.html'), name='help_update_pan_tilt'),
    url(r'^help/schedule/$', TemplateView.as_view(template_name='imscam/help/schedule.html'), name='help_schedule'),
    
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#import ptz_control
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

handler404 = 'imscam.views.custom_404'
handler500 = 'imscam.views.custom_500'

urlpatterns = patterns('',
    # Examples:
    url(r'^$', RedirectView.as_view(url='/imscam/')),
    
    url(r'^imscam/', include('imscam.urls', namespace='imscam')),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    #url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
     #   'document_root': settings.MEDIA_ROOT,
    #}),
)
#urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

src/imscam/views.py
import base64
import StringIO
from datetime import datetime
import os
from os import path, listdir
from os.path import isfile, join
from shutil import copyfileobj, copyfile
from PIL import Image
import uuid
import time
import json
import tempfile
from itertools import chain
import logging
from subprocess import Popen, PIPE
import cStringIO

from django.conf import settings as django_settings
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import permission_required
from django.contrib.sessions.models import Session
from django.contrib.sessions.backends.db import SessionStore
from django.core import serializers
from django.core.management import call_command
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models.fields import AutoField
from django.forms.models import inlineformset_factory
from django.http import HttpResponse, HttpResponseRedirect, StreamingHttpResponse, HttpResponseForbidden
from django.shortcuts import render_to_response, get_object_or_404, render
from django.template.context import RequestContext
from django.template.loader import render_to_string
from django.utils import simplejson
from django.views.decorators.cache import never_cache

from django_sse.views import BaseSseView

from imscam import models, settings, forms
from imscam.settings import CAM_DRIVER, PTZ_DRIVER
from imscam.forms import GroupForm, LocationForm, ImageSettingForm
from imscam.utils import JsonResponse



IMG_ROOT = settings.GROUPS_IMG_ROOT

if not os.path.exists(settings.PREVIEW_TMP_ROOT):
    os.makedirs(settings.PREVIEW_TMP_ROOT) 

logger = logging.getLogger(__name__)


def custom_404(request):
    return render(request,'imscam/404.html') 
def custom_500(request):
    return render(request,'imscam/500.html') 

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                next = request.REQUEST.get('next', reverse('imscam:index'))
                logger.debug("next: %s" % next)
                return JsonResponse({'next': next})
            else:
                # Return a 'disabled account' error message
                pass
        else:
            # Return an 'invalid login' error message.
            return HttpResponseForbidden()
    else:
        return render(request, "imscam/login.html", {})

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('imscam:index'))

def index(request):
    groups = models.Group.objects.filter(deleted=False)
    group = groups.filter(default=True)[0]
    locations = group.location_set.filter(deleted=False)
    capturetime = models.CaptureTime.objects.get(default=True)
    
    
    sessions = Session.objects.filter(expire_date__gte=datetime.now())
    active_preview_sessions = []
    for session in sessions:
        data = session.get_decoded()
        if data.get('preview-started', False):
            active_preview_sessions.append(session.session_key)
    #print active_preview_sessions
    if request.session.get("preview-started") and len(active_preview_sessions) == 1:
        CAM_DRIVER.stop_preview()
    request.session["preview-started"] = False    
    
    if request.user.has_perm("imscam.change_settings"):
        form = forms.GroupForm(instance=group)
        capturetime_form = forms.CaptureTimeForm(instance=capturetime)
    else:
        form = forms.GroupFormReadOnly(instance=group)
        capturetime_form = forms.CaptureTimeFormReadOnly(instance=capturetime)
    
 
    context = {'language': django_settings.LANGUAGE_CODE,
               'form': form, 
               'capturetime_form': capturetime_form,
               'location_list': locations,
                    'groups': groups,
                   'group': group,
                   'default_capturetime':capturetime,
                   'preview_settings': CAM_DRIVER.get_preview_settings(),
                   'MEDIA_PREVIEW': settings.MEDIA_PREVIEW}
    context['group_id'] = group.id
    context['PTZ_DRIVER'] = PTZ_DRIVER
    unsaved_locations = request.session.get("new-locations_%s" % group.id)
    
    logger.debug("unsaved_locations from index")
    logger.debug(unsaved_locations)
    #print unsaved_locations        
    if unsaved_locations:
        for session_loc in unsaved_locations:
        #for random in unsaved_locations:
            logger.debug("loading unsaved location from session")
            loc = models.Location()
            loc.random = session_loc[0]
            loc.tmp_pan = session_loc[1][0]
            loc.tmp_tilt = session_loc[1][1]
            context['location_list'] = list( chain( context['location_list'], [loc] ) )
        
    return render(request, 'imscam/index.html', context)


class SsePreviewEvents(BaseSseView):
    def iterator(self):
        #print self.request
        interval = self.request.GET.get('interval')
        interval_sec = float(interval) / 1000
        if CAM_DRIVER.get_name() == 'dummy' and interval_sec == 0:
            interval_sec = 0.5
        while True:
            try:
                preview_running = CAM_DRIVER.preview_running()
                if not preview_running:
                    self.sse.add_message("preview-stopped", "live preview has been stopped")
                    break
                img = CAM_DRIVER.get_preview_image((600,400))
                if img:
                    output = StringIO.StringIO()
                    img.save(output, format="JPEG")
                    contents = output.getvalue()
                    output.close()
                    b64_img = base64.b64encode(contents)
                    
                    self.sse.add_message("preview-img", b64_img)
                time.sleep(interval_sec)
            except Exception, e:
                logger.error("error in SsePreviewEvents")
                logger.error(e)
                self.sse.add_message("error", "live preview has been stopped")
                break
            finally:
                yield
        
            


@never_cache
@permission_required('imscam.view_liveimage')
def get_preview_img(request):
    
    """started = False
    for s in Session.objects.all():
        if s.get_decoded().get("preview_started"):
            started = True"""
            
    #preview_state = models.LivePreviewState.objects.all()[0]
    preview_running = CAM_DRIVER.preview_running()
    
    #if not preview_state.running:
    if not preview_running:
        return HttpResponse("live preview has been stopped", status=410)
    
    try:
        #img = CAM_DRIVER.get_resized_image_PIL(600, 400)
        img = CAM_DRIVER.get_preview_image((600,400))
        if not img:
            return HttpResponse()
        output = StringIO.StringIO()
        img.save(output, format="JPEG")
        contents = output.getvalue()
        output.close()
        
        b64_img = base64.b64encode(contents)
        return HttpResponse(b64_img)
    except Exception, e:
        #preview_state.running = False
        #preview_state.save()
        return HttpResponse(str(e), status=410)

  
    
@permission_required('imscam.view_liveimage')    
def start_preview(request):
    if request.method == 'POST':
        
        #preview_state = models.LivePreviewState.objects.all()[0]
        preview_running = CAM_DRIVER.preview_running()
        
        #if preview_state.running:
        if preview_running:
            logger.debug('preview already started')
            return JsonResponse({'success':True, 'msg': 'preview already started'})
        
        if PTZ_DRIVER:
            PTZ_DRIVER.reset()
        
        try:
            CAM_DRIVER.start_preview()
            request.session["preview-started"] = True
        except Exception as e:
            return JsonResponse({'msg':e.message})
        
        return JsonResponse({'success':True, 'msg':'started preview', 'pan':PTZ_DRIVER.getPan(), 'tilt':PTZ_DRIVER.getTilt()})
        #return HttpResponse('started preview')
    return HttpResponse('start_preview with GET')

@permission_required('imscam.view_liveimage')    
def stop_preview(request):
    if request.method == 'POST':
        #print "enter stop_preview()"
        #preview_state = models.LivePreviewState.objects.all()[0]
        preview_running = CAM_DRIVER.preview_running()
    
        if not preview_running:
            return HttpResponse("already stopped preview")
        
        try:
            #print "capture image"
            img = CAM_DRIVER.get_preview_image((600, 400))
            img.save(settings.PREVIEW_FULL_PATH)
        except Exception as e:
            print "exception capture"
            print e
        try:
            
            sessions = Session.objects.filter(expire_date__gte=datetime.now())
            active_preview_sessions = []
            for session in sessions:
                data = session.get_decoded()
                if data.get('preview-started', False):
                    active_preview_sessions.append(session.session_key)
            #print active_preview_sessions
            if request.session.get("preview-started") and len(active_preview_sessions) == 1:
                #print "delegate stop_preview"
                CAM_DRIVER.stop_preview()
                #if PTZ_DRIVER:
                #    print "resetting PTZ_DRIVER"
                #    PTZ_DRIVER.reset()
            request.session["preview-started"] = False
        except Exception as e:
            print e    
        
        return HttpResponse('stopped preview')
    return HttpResponse('stop_preview with GET') 

def copy_preview(request):
    if request.method == "POST":
        group_id = request.POST.get("group_id")

src/imscam/templates/imscam/include/settings/group_location_form.html
<div id="group-location-form-panel" class="panel panel-default">
    <div class="panel-heading">
        <a href="#" class="collapse-section">
            <span class="glyphicon glyphicon-chevron-down"></span>
        
        {% if group %}
            {% if group.id %}
                <strong>group</strong> settings for <strong>{% firstof group.name "NEW" %}</strong>
            {% else %}
                New group
            {% endif %}
        {% elif location %}
            {% if location.id %}
                <strong>location</strong> settings for <strong>{% firstof location.name "NEW" %}</strong>
            {% else %}
                New location
            {% endif %}
        {% endif %}
        </a>
    </div>
    <div class="panel-body">
	    <form id="group-location-form" class="form-horizontal" role="form">
	        {% csrf_token %}
	        
	        <div id="form-errors" class="alert alert-danger" hidden="hidden">
	        </div>
            
	        {% for field in form.visible_fields %}
			    <div class="form-group" {% if location %}style="margin-bottom: 4px;"{% endif %}>
			        <div class="control-label col-md-3 col-sm-4">
			            {{ field.label_tag }}
			        </div>
			        <div class="col-sm-9 col-sm-8">
			            {{ field }}
			        </div>
			    </div>
			{% endfor %}
			{% if location and location.pan %}
			    <div class="form-group" style="margin-left: 15px;">
                    <small><strong>pan:</strong> <span id="location_pan">{{ location.pan }}</span>, <strong>tilt:</strong> <span id="location_tilt">{{ location.tilt }}</span></small>
                </div>
			{% endif %}
			
			
			<div class="panel panel-default settings-panel">
                <div class="panel-heading">
                    <ul class="nav nav-tabs">   
                        <li class="active"><a href="#scheduler-settings">Scheduler settings</a></li>
                        {% if location %}
                            <li><a href="#image-settings">Image settings</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="panel-body">
                    <div id='content' class="tab-content">
		                <div class="tab-pane active" id="scheduler-settings">
		                    {% include 'imscam/include/settings/scheduling_settings.html' %}
		                </div>
		                {% if location %}
		                    <div class="tab-pane" id="image-settings">
		                        {% include 'imscam/include/settings/image_settings.html' %}
		                    </div>
		                {% endif %}
		            </div>        
                </div>
            </div>

		        
			
            
	        <input type="hidden" value="{{ form.instance.id }}" name="id"></input>
	        <input type="hidden" value="{{ form.instance.pan }}" name="pan"></input>
	        <input type="hidden" value="{{ form.instance.tilt }}" name="tilt"></input>
	    </form>
    </div>
    <div class="panel-footer">
        {% if group %}
            {% if group.id %}
                    <button type="submit" id="group-form-submit" data-url="{% url 'imscam:group_edit' group.id %}" {% if not 'imscam.change_settings' in perms %}disabled='disabled'{% endif %} class="btn btn-primary btn-sm">Save changes</button>
                {% else %}
                    <button type="submit" id="group-form-submit" data-url="{% url 'imscam:group_new' %}" {% if not 'imscam.change_settings' in perms %}disabled='disabled'{% endif %} class="btn btn-primary btn-sm">Create group</button>
            {% endif %}
        {% elif location %}
            {% if location.id %}
	            <button id="location-form-submit" type="submit" data-url="{% url 'imscam:location_edit' location.group.id location.id %}" {% if not 'imscam.change_settings' in perms %}disabled='disabeld'{% endif %} class="btn btn-primary btn-sm">Save changes</button>
	        {% else %}
	            <button id="location-form-submit" type="submit" data-url="{% url 'imscam:location_new' group_id %}" {% if not 'imscam.change_settings' in perms %}disabled='disabeld'{% endif %} class="btn btn-primary btn-sm">Create location</button>
	        {% endif %}
        {% endif %}
        
        <button id="form-close" type="button" class="btn btn-default btn-sm">close</button>
    </div>
</div>

src/imscam/templates/imscam/include/settings/image_settings.html
{% for field in image_settings_form.visible_fields %}
    <div class="form-group">
        <div class="col-sm-5">
            {{ field.label_tag }}
        </div>
        <div class="col-sm-7">
            {{ field }}
        </div>
    </div>
{% endfor %}

src/imscam/templates/imscam/include/settings/play_pause_form.html
<form class="play-pause-form form-horizontal" action="{% url 'imscam:play_pause' %}" method="POST" role="form" style="display:inline-block;">
    <input type="hidden" name="id" value="{% firstof instance.capture_time.id capture_time.id %}" />
    
    {% if not instance %}
        <div class="default"></div>
    {% elif instance.group %}
        <div class="location"></div>
    {% else %}
        <div class="group"></div>
    {% endif %}
    <span class="tooltip-elem" data-toggle="tooltip" data-placement="top"
        {% if not instance %}
            title="Schedule to take automatically images of scheduled groups"
        {% elif instance.group %}
            title="Schedule to take automatically images"
        {% else %}
            title="Schedule to take automatically images of scheduled locations"
        {% endif %} 
        
    >
	    {% if not instance %}
	        <button type="button" 
	                id="{{ capture_time.id }}_enabled"
	                class="scheduler-enabler btn btn-default btn-xs {% if capture_time.enabled %} active {% endif %}" 
	                data-toggle="button"
	                name="{{ capture_time.id }}_enabled" 
	                {% if not 'imscam.change_settings' in perms %} disabled="disabled" {% endif %}>
	            {% if capture_time.default %}
	                <small>All groups scheduled</small>
	            {% else %}
	                <small>Scheduled</small>
	            {% endif %}
	        </button>
	    {% else %}
	        <button type="button" 
	                id="{{ instance.capture_time.id }}_enabled"
	                class="scheduler-enabler btn btn-default btn-xs {% if instance.capture_time.enabled %} active {% endif %}" 
	                data-toggle="button"
	                name="{{ instance.capture_time.id }}_enabled" 
	                {% if not 'imscam.change_settings' in perms %} disabled="disabled" {% endif %}>
	            {% if instance.capture_time.default %}
	                <small>All groups scheduled</small>
	            {% else %}
	                <small>Scheduled</small>
	            {% endif %}
	        </button>
	    {% endif %}
    </span>             
</form>

src/imscam/templates/imscam/include/settings/preview_cam_settings.html
<div class="col-lg-12 preview-settings">
    <small>
        {% for name, setting in preview_settings.items %}
            <div class="preview-setting" style="display:inline-block;">
                <!-- <input type="hidden" name="config" value="{{ setting.config }}"></input>  -->
                <span>{{ name }}:</span><br />
                {% if setting.type == 'choice' %}
                    <select data-name="{{ name }}" data-url="{% url 'imscam:set_config' %}">
                        {% for choice in setting.choices %}
                            <!-- <option {% if forloop.counter0 == setting.cur_index %}selected{% endif %}>  -->
                            <option value="{{ choice.0 }}" {% if setting.current == choice.0 %}selected{% endif %}>{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                {% endif %}
            </div>
        {% endfor %}
    </small>
</div>

src/imscam/templates/imscam/include/settings/scheduling_settings.html
<div class="form-group">
    <div class="col-sm-6 ">
        {{ capturetime_form.enabled.label_tag }}
    </div>
    <div class="col-sm-6">
        {{ capturetime_form.enabled }}
    </div>
</div>
{% if not default_setting %}
	<div class="form-group">
	    <div class="col-md-6">
	        {{ capturetime_form.start_date.label_tag }}
	    </div>
	    <div class="col-md-6">
	        {{ capturetime_form.start_date }}
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-md-6 ">
	        {{ capturetime_form.end_date.label_tag }}
	    </div>
	    <div class="col-md-6">
	        {{ capturetime_form.end_date }}
	    </div>
	</div>
{% endif %}
<div class="form-group">
    <div class="col-md-6 ">
        {{ capturetime_form.start_time.label_tag }}
    </div>
    <div class="col-md-6">
        {{ capturetime_form.start_time }}
    </div>
</div>
<div class="form-group">
    <div class="col-md-6 ">
        {{ capturetime_form.end_time.label_tag }}
    </div>
    <div class="col-md-6">
        {{ capturetime_form.end_time }}
    </div>
</div>
<div class="form-group">
    <div class="col-md-6 ">
        {{ capturetime_form.interval.label_tag }}
    </div>
    <div class="col-md-6">
        {{ capturetime_form.interval }}
    </div>
</div>
<div id="from-to-days" class="form-group">    			
	<div class="btn-group" data-toggle="buttons">
	    <label class="btn btn-default {% if capturetime_form.instance.monday %}active{% endif %} {% if not 'imscam.change_settings' in perms %}disabled{% endif %}">
	        {{ capturetime_form.monday }} Mo
	    </label>
	    <label class="btn btn-default {% if capturetime_form.instance.tuesday %}active{% endif %} {% if not 'imscam.change_settings' in perms %}disabled{% endif %}">
	        {{ capturetime_form.tuesday }} Tu
	    </label>
	    <label class="btn btn-default {% if capturetime_form.instance.wednesday %}active{% endif %} {% if not 'imscam.change_settings' in perms %}disabled{% endif %}">
	        {{ capturetime_form.wednesday }} We
	    </label>
	    <label class="btn btn-default {% if capturetime_form.instance.thursday %}active{% endif %} {% if not 'imscam.change_settings' in perms %}disabled{% endif %}">
	        {{ capturetime_form.thursday }} Th
	    </label>
	    <label class="btn btn-default {% if capturetime_form.instance.friday %}active{% endif %} {% if not 'imscam.change_settings' in perms %}disabled{% endif %}">
	        {{ capturetime_form.friday }} Fr
	    </label>
	    <label class="btn btn-default {% if capturetime_form.instance.saturday %}active{% endif %} {% if not 'imscam.change_settings' in perms %}disabled{% endif %}">
	        {{ capturetime_form.saturday }} Sa
	    </label>
	    <label class="btn btn-default {% if capturetime_form.instance.sunday %}active{% endif %} {% if not 'imscam.change_settings' in perms %}disabled{% endif %}">
	        {{ capturetime_form.sunday }} Su
	    </label>
	</div>
</div>	    			
{% if group and group.id or default_setting %}
    <div class="form-group">
	    <div class="col-md-6">
	        <label for="overwrite">Overwrite {% if group %}location{% else %}group{% endif %} settings </label>
	    </div>
	    <div class="col-md-6">
	        <input id="overwrite" name="overwrite_group_locations" type="checkbox" {% if not 'imscam.change_settings' in perms %}disabled{% endif %}/>
	    </div>   				        
	    <div class="col-xs-12"><small>Existing {% if group %}location{% else %}group{% endif %} settings won't change unless checked</small></div>
	</div>
{% endif %}
<div class="clearfix"></div>